In [ ]:
d=iter([1,2,3,4])
next(d)

1

In [ ]:
next(d)

2

In [ ]:
next(d)

3

In [ ]:
next(d)

4

In [ ]:
next(d)

2

In [ ]:

next(d)

(3, 4)

In [ ]:
d=iter('abc')

In [ ]:
next(d)

'a'

In [ ]:
next(d)

'b'

In [ ]:
next(d)

'c'

In [ ]:
d=iter({'name':'jhon','age':'25'})

next(d)

'name'

In [ ]:
next(d)

'age'

In [ ]:
import time
now = time.time()
print(now)

1676206776.5141456


In [ ]:
import time
now = time.asctime(time.localtime())
print(now)

Sun Feb 12 21:10:47 2023


In [ ]:
import threading
class threadTest(threading.Thread):              #类必须继承threading.Thread
    
    def __init__(self, args) -> None:            #args为传入线程的参数，可根据自己的需求进行定义
        
        super(threadTest, self).___init__()      #初始化super()内的必须与类名一样
        self.args = args
    
    def run(self) -> None:                      #定义run()方法，主要写线程的执行内容
        print('test thread running......')
        print('args:', self.args)
        return super().run()
    
if __name__ == '__main__':
    test = threadTest('just test')              #实例化
    test.start()                                #启动线程，即运行run()方法

: 

In [1]:
import torch
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y  # **运算符是求幂运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [2]:
torch.exp(x)    #“按元素”方式可以应用更多的计算，包括像求幂这样的一元运算符

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [8]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)      #可以把多个张量连结（concatenate）在一起， 把它们端对端地叠起来形成一个更大的张量

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [9]:
X[-1], X[1:3]       #用[-1]选择最后一个元素，可以用[1:3]选择第二个和第三个元素

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [12]:
X[1, 2] =9      #可以通过指定索引来将元素写入矩阵。
X


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [7]:
#广播机制
# 通过适当复制元素来扩展一个或两个数组，以便在转换之后，两个张量具有相同的形状；
# 对生成的数组执行按元素操作。
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b


(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [6]:
a+b         #矩阵a将复制列， 矩阵b将复制行，然后再按元素相加。

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [13]:
before = id(Y)      #id() 函数返回对象的唯一标识符，标识符是一个整数。
Y = Y+X
id(Y) == before

False

In [14]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 140344123278736
id(Z): 140344123278736


In [15]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [16]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [21]:
import os 

os.makedirs(os.path.join('..', 'data'), exist_ok= True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms, Alley, Price\n')
    f.write('NA,Pave,127500\n')
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA, NA, 140000\n')

In [22]:
import pandas as pd
    
data = pd.read_csv(data_file)
print(data)

   NumRooms  Alley   Price
0       NaN   Pave  127500
1       2.0    NaN  106000
2       4.0    NaN  178100
3       NaN     NA  140000


In [23]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [24]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [25]:
B = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [26]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [27]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [28]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()     #通过分配新内存，将A的一个副本分配给B
A, A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [29]:
# 两个矩阵的按元素乘法称为Hadamard积（Hadamard product）
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [30]:
#将张量乘以或加上一个标量不会改变张量的形状，其中张量的每个元素都将与标量相加或相乘
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a*X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [31]:
##降维
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [32]:
A.shape, A.sum()

(torch.Size([5, 4]), tensor(190.))

In [33]:
A_sum_axis0 = A.sum(axis=0)             #通过求和所有行的元素来降维（轴0），可以在调用函数时指定axis=0
A_sum_axis0, A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [34]:
#指定axis=1将通过汇总所有列的元素降维（轴1）
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))